// Aspie Quiz v5 Questions - Grouped by Domain
// Domains: Talent, Perception, Communication, Relationships, Social (based on Aspie Quiz scoring)
QUESTIONS.aspie = [
    // TALENT DOMAIN - Special interests, pattern recognition, detail orientation
    { id: 'as3', group: "Talent", q: "When you listen to music can you get so caught up in it that you don't notice anything else?" },
    { id: 'as16', group: "Talent", q: "Can things that might seem meaningless to others make sense to you?" },
    { id: 'as29', group: "Talent", q: "Are you often delighted by small things (like the colors in soap bubbles and the five pointed star shape that appears when you cut an apple across the core)?" },
    { id: 'as40', group: "Talent", q: "Do you notice patterns in things all the time?" },
    { id: 'as47', group: "Talent", q: "Are you still fascinated by many of the things you were interested in when you were much younger?" },
    { id: 'as55', group: "Talent", q: "Do you have one special talent which you have emphasised and worked on?" },
    { id: 'as57', group: "Talent", q: "Do you need to do things yourself in order to remember them?" },
    { id: 'as70', group: "Talent", q: "Do you have an avid perseverance in gathering and/or cataloguing information on a topic of interest?" },
    { id: 'as73', group: "Talent", q: "Do you have an urge to observe the habits of humans and/or animals?" },
    { id: 'as78', group: "Talent", q: "Is your sense of humor different from mainstream or considered odd?" },
    { id: 'as93', group: "Talent", q: "Do you have a fascination for slowly flowing water?" },
    { id: 'as98', group: "Talent", q: "Is it important for you to find a unique niche where you can acquire unique competence?" },
    { id: 'as100', group: "Talent", q: "Do you tend to get so absorbed by your special interests that you forget or ignore everything else?" },
    { id: 'as106', group: "Talent", q: "Do you prefer to construct your own set of spiritual beliefs rather than following existing religions / belief-systems?" },
    { id: 'as112', group: "Talent", q: "Do you feel that you are a very special or unusual person?" },
    { id: 'as114', group: "Talent", q: "Do you tend to play the same tune many times in a row?" },
    { id: 'as115', group: "Talent", q: "Do you fail to understand pop culture, things like 'being in style' or why people jump onto the latest trend?" },

    // PERCEPTION DOMAIN - Sensory sensitivity, routine, predictability
    { id: 'as6', group: "Perception", q: "Do you have extra sensitive hearing?" },
    { id: 'as9', group: "Perception", q: "Do you tend to shut down or have a meltdown when stressed or overwhelmed?" },
    { id: 'as12', group: "Perception", q: "Are you bothered by clothes tags or light touch?" },
    { id: 'as15', group: "Perception", q: "Do you enjoy travel?" },
    { id: 'as18', group: "Perception", q: "Do you dislike it when people stamp their foot in the floor?" },
    { id: 'as20', group: "Perception", q: "Do you like to create routines for things you've figured out so you don't have to figure it out again?" },
    { id: 'as28', group: "Perception", q: "Do you notice odors that other people don't seem to notice?" },
    { id: 'as32', group: "Perception", q: "If there is an interruption, can you quickly return to what you were doing before?" },
    { id: 'as35', group: "Perception", q: "Do you need to prepare yourself mentally before going somewhere?" },
    { id: 'as41', group: "Perception", q: "Are you sensitive to changes in humidity and air pressure?" },
    { id: 'as56', group: "Perception", q: "Do you instinctively become frightened by the sound of a motor-bike?" },
    { id: 'as61', group: "Perception", q: "Do you enjoy big events even if they are crowded?" },
    { id: 'as63', group: "Perception", q: "Do you dislike it when people drop by to visit you uninvited?" },
    { id: 'as67', group: "Perception", q: "Do you find it difficult to engage in a task of no interest to you even if it is important?" },
    { id: 'as68', group: "Perception", q: "Do you have eyes extra sensitive to strong light and glare?" },
    { id: 'as72', group: "Perception", q: "Have you sensed that somebody was around you even when you couldn't see anybody?" },
    { id: 'as77', group: "Perception", q: "Do you have difficulties judging distances, height, depth or speed?" },
    { id: 'as85', group: "Perception", q: "Do you dislike being hugged when you haven't asked for it?" },
    { id: 'as89', group: "Perception", q: "Do you dislike when people walk behind you?" },
    { id: 'as96', group: "Perception", q: "Do you have a good sense of how much pressure to apply when doing things with your hands?" },
    { id: 'as97', group: "Perception", q: "Do you have problems finding your way to new places?" },
    { id: 'as109', group: "Perception", q: "Do you have trouble reading clocks?" },
    { id: 'as110', group: "Perception", q: "Do you have a good sense of time?" },

    // COMMUNICATION DOMAIN - Verbal/nonverbal communication, stimming
    { id: 'as10', group: "Communication", q: "Is is difficult to pass on messages correctly?" },
    { id: 'as21', group: "Communication", q: "Do you expect other people to know your thoughts, experiences and opinions without you having to tell them?" },
    { id: 'as23', group: "Communication", q: "Do you rock back-&-forth or side-to-side (e.g. for comfort, to calm yourself, when excited or overstimulated)?" },
    { id: 'as24', group: "Communication", q: "Do you have difficulty describing & summarising things for example events, conversations or something you've read?" },
    { id: 'as26', group: "Communication", q: "In conversations, do you need extra time to carefully think out your reply, so that there may be a pause before you answer?" },
    { id: 'as27', group: "Communication", q: "Do you avoid talking because you cannot reliably predict how others will react, especially strangers?" },
    { id: 'as31', group: "Communication", q: "Do you practice what you want to say in conversations?" },
    { id: 'as33', group: "Communication", q: "In a conversation, do you tend to focus on your own thoughts rather than on what your listener might be thinking?" },
    { id: 'as37', group: "Communication", q: "Do you tend to say things that are considered socially inappropriate when you are tired, frustrated or when you act naturally?" },
    { id: 'as43', group: "Communication", q: "Do people sometimes think you are smiling at the wrong occasion?" },
    { id: 'as44', group: "Communication", q: "Do you find it easy to describe your feelings?" },
    { id: 'as49', group: "Communication", q: "Do you tend to wander off the topic when having a conversation?" },
    { id: 'as50', group: "Communication", q: "Do others often misunderstand you?" },
    { id: 'as51', group: "Communication", q: "Do you wring your hands, rub your hands together or twirl your fingers?" },
    { id: 'as52', group: "Communication", q: "Do you find it easy to keep up with group discussions where everyone is speaking?" },
    { id: 'as58', group: "Communication", q: "Have you been accused of staring?" },
    { id: 'as59', group: "Communication", q: "Do you have problems filling out forms?" },
    { id: 'as60', group: "Communication", q: "Do you tap your ears or press your eyes (e.g. when thinking, when stressed or distressed)?" },
    { id: 'as65', group: "Communication", q: "Do you get confused by several verbal instructions at the same time?" },
    { id: 'as66', group: "Communication", q: "Do you have problems with timing in conversations?" },
    { id: 'as71', group: "Communication", q: "Do you find it natural to wave or say 'hi' when you meet people?" },
    { id: 'as74', group: "Communication", q: "Do you find it difficult to take notes in lectures?" },
    { id: 'as80', group: "Communication", q: "Do you tend to express your feelings in ways that may baffle others?" },
    { id: 'as81', group: "Communication", q: "Do you instinctively know when it is your turn to speak when talking on the phone?" },
    { id: 'as82', group: "Communication", q: "Can you easily remember verbal instructions?" },
    { id: 'as83', group: "Communication", q: "Do you have an urge to jump over things?" },
    { id: 'as84', group: "Communication", q: "Have others told you that you have an odd posture or gait?" },
    { id: 'as91', group: "Communication", q: "Do you enjoy spinning in circles?" },
    { id: 'as95', group: "Communication", q: "Do you pace (e.g. when thinking or anxious)?" },
    { id: 'as99', group: "Communication", q: "Do you tend to interpret things literally?" },
    { id: 'as107', group: "Communication", q: "Do you feel an urge to peel flakes off yourself and / or others?" },
    { id: 'as108', group: "Communication", q: "Is your sense of humor fairly conventional?" },
    { id: 'as111', group: "Communication", q: "Do you bite your lip, cheek or tongue (e.g. when thinking, when anxious or nervous)?" },
    { id: 'as117', group: "Communication", q: "Do you cry about nothing?" },

    // RELATIONSHIPS DOMAIN - Attachments, dating, intimacy
    { id: 'as7', group: "Relationships", q: "Have you experienced stronger than normal attachments to certain people?" },
    { id: 'as11', group: "Relationships", q: "Do you have, or used to have, imaginary relationships?" },
    { id: 'as19', group: "Relationships", q: "Are you asexual?" },
    { id: 'as22', group: "Relationships", q: "Do you have unusual sexual preferences?" },
    { id: 'as30', group: "Relationships", q: "Have you been talked into having sex even if you really didn't want to?" },
    { id: 'as34', group: "Relationships", q: "Do you prefer to learn the character of a potential romantic partner through observation rather than conversation?" },
    { id: 'as54', group: "Relationships", q: "Do you examine the hair of people you like a lot?" },
    { id: 'as62', group: "Relationships", q: "Do you find yourself at ease in romantic situations?" },
    { id: 'as69', group: "Relationships", q: "Do you like tongue-kissing?" },
    { id: 'as75', group: "Relationships", q: "Do you realize hours later that somebody that you have a romantic interest for actually showed interest for you, and then feel bad about the missed opportunity to connect?" },
    { id: 'as76', group: "Relationships", q: "Do you tend to look a lot at people you like and little or not at all at people you dislike?" },
    { id: 'as90', group: "Relationships", q: "Do you like to protect people you are attached to even when they didn't ask for it?" },
    { id: 'as92', group: "Relationships", q: "Do you enjoy traditional dating?" },
    { id: 'as103', group: "Relationships", q: "Do you like to follow (walk behind) people you are attached to?" },
    { id: 'as104', group: "Relationships", q: "Do you have obsessive attachments to animate objects?" },
    { id: 'as116', group: "Relationships", q: "Do you tend to get romantic feelings for people that persistently shows interest for you?" },
    { id: 'as118', group: "Relationships", q: "Do you naturally approach somebody you have an romantic interest for?" },

    // SOCIAL DOMAIN - Social skills, friendships, group dynamics
    { id: 'as1', group: "Social", q: "Do you usually find faults with opinions that you don't share?" },
    { id: 'as2', group: "Social", q: "Do you find it easy to estimate the age of people?" },
    { id: 'as4', group: "Social", q: "Do you feel you have to be on your guard even with friends?" },
    { id: 'as5', group: "Social", q: "As a teenager, were you usually unaware of social rules & boundaries unless they were clearly spelled out?" },
    { id: 'as8', group: "Social", q: "Will you abandon your friends if your activities or ideals clash?" },
    { id: 'as13', group: "Social", q: "Is it hard for you to see why some things upset people so much?" },
    { id: 'as14', group: "Social", q: "Are you good at team-work?" },
    { id: 'as17', group: "Social", q: "Are you shy?" },
    { id: 'as25', group: "Social", q: "Has it been harder for you than for others to keep friends?" },
    { id: 'as36', group: "Social", q: "Do you feel as if you are being persecuted in some way?" },
    { id: 'as38', group: "Social", q: "Do you feel irritated when one person disagrees with what everyone else in a group believes?" },
    { id: 'as39', group: "Social", q: "Do you prefer to only meet people you know, one-on-one, or in small, familiar groups?" },
    { id: 'as42', group: "Social", q: "Do you have to keep an eye out to stop people from taking advantage of you?" },
    { id: 'as45', group: "Social", q: "Do you accept criticism, correction and direction?" },
    { id: 'as46', group: "Social", q: "Do you worry your friend doesn't really like you?" },
    { id: 'as48', group: "Social", q: "Do you find it hard to tell the age of people?" },
    { id: 'as53', group: "Social", q: "Would you quickly become impatient and irritated if you would not find a solution to a problem?" },
    { id: 'as64', group: "Social", q: "Do you need a lot of motivation to do things?" },
    { id: 'as79', group: "Social", q: "Do you like 'being in style'?" },
    { id: 'as86', group: "Social", q: "Did you feel lonely as a child?" },
    { id: 'as87', group: "Social", q: "Do you find it easier to understand and communicate with odd & unusual people than with ordinary people?" },
    { id: 'as88', group: "Social", q: "Do you prefer to do things on your own even if you could use others' help or expertise?" },
    { id: 'as94', group: "Social", q: "Do you recognize a lot of people?" },
    { id: 'as101', group: "Social", q: "Are you good at interpreting facial expressions?" },
    { id: 'as102', group: "Social", q: "Do you like to have small talk before getting on to the important topics in a conversation?" },
    { id: 'as105', group: "Social", q: "Do you spend hours overthinking and re-enacting negative social interaction?" },
    { id: 'as113', group: "Social", q: "Do you have difficulty accepting criticism, correction, and direction?" },
    { id: 'as119', group: "Social", q: "Do you see your own activities as more important than other people's?" }
];
