// Test Configuration
const TEST_CONFIG = [
    { id: 'adhd_rs', title: 'ADHD-RS-IV', description: 'Adult ADHD Rating Scale with Prompts (Current Symptoms)', scale: ['None', 'Mild', 'Moderate', 'Severe'] },
    { id: 'wurs', title: 'Wender Utah', description: 'WURS - Retrospective Childhood ADHD Symptoms', scale: ['Not at all or very slightly', 'Mildly', 'Moderately', 'Quite a bit', 'Very much'] },
    { id: 'sasi', title: "Women's SASI", description: 'Symptom Inventory for Women (Childhood & Adult)', scale: ['0 - Not at All', '1 - A Little', '2 - A Lot', '3 - Just Like Me'] },
    { id: 'aq', title: 'Autism Quotient', description: 'Autism Spectrum Quotient (AQ)', scale: ['Definitely Agree', 'Slightly Agree', 'Slightly Disagree', 'Definitely Disagree'] },
    { id: 'aspie', title: 'Aspie Quiz v5', description: 'Broad Autism Spectrum Traits Assessment (Version 5)', scale: ['No / Never', 'A Little', 'Yes / Often', "Don't Know"] }
];

// All Questions organized by test
const QUESTIONS = {
    adhd_rs: [
        { id: 'a1_1', part: "Inattention Symptoms", group: "1. Carelessness", q: "Do you make a lot of mistakes (in school or work)?" },
        { id: 'a1_2', part: "Inattention Symptoms", group: "1. Carelessness", q: "Is this because you're careless?" },
        { id: 'a1_3', part: "Inattention Symptoms", group: "1. Carelessness", q: "Do you rush through work or activities?" },
        { id: 'a1_4', part: "Inattention Symptoms", group: "1. Carelessness", q: "Do you have trouble with detailed work?" },
        { id: 'a1_5', part: "Inattention Symptoms", group: "1. Carelessness", q: "Do you not check your work?" },
        { id: 'a1_6', part: "Inattention Symptoms", group: "1. Carelessness", q: "Do people complain that you're careless?" },
        { id: 'a1_7', part: "Inattention Symptoms", group: "1. Carelessness", q: "Are you messy or sloppy?" },
        { id: 'a1_8', part: "Inattention Symptoms", group: "1. Carelessness", q: "Is your desk or workspace so messy that you have difficulty finding things?" },
        { id: 'a2_1', part: "Inattention Symptoms", group: "2. Difficulty sustaining attention", q: "Do you have trouble paying attention when watching movies, reading, or attending lectures?" },
        { id: 'a2_2', part: "Inattention Symptoms", group: "2. Difficulty sustaining attention", q: "Do you have trouble paying attention on fun activities such as sports or board games?" },
        { id: 'a2_3', part: "Inattention Symptoms", group: "2. Difficulty sustaining attention", q: "Is it hard for you to keep your mind on school or work?" },
        { id: 'a2_4', part: "Inattention Symptoms", group: "2. Difficulty sustaining attention", q: "Do you have unusual trouble staying focused on boring or repetitive tasks?" },
        { id: 'a2_5', part: "Inattention Symptoms", group: "2. Difficulty sustaining attention", q: "Does it take a lot longer than it should to complete tasks because you can't keep your mind on the task?" },
        { id: 'a2_6', part: "Inattention Symptoms", group: "2. Difficulty sustaining attention", q: "Is it even harder for you than some others you know?" },
        { id: 'a2_7', part: "Inattention Symptoms", group: "2. Difficulty sustaining attention", q: "Do you have trouble remembering what you read and do you need to re-read the same passage several times?" },
        { id: 'a3_1', part: "Inattention Symptoms", group: "3. Doesn't listen", q: "Do people (spouse, boss, colleagues, friends) complain that you don't seem to listen or respond (or daydream) when spoken to? A lot?" },
        { id: 'a3_2', part: "Inattention Symptoms", group: "3. Doesn't listen", q: "Do people have to repeat directions?" },
        { id: 'a3_3', part: "Inattention Symptoms", group: "3. Doesn't listen", q: "Do you find that you miss the key parts of conversations because of drifting off in your own thoughts?" },
        { id: 'a4_1', part: "Inattention Symptoms", group: "4. No follow through", q: "Do you have trouble finishing things (such as work or chores)?" },
        { id: 'a4_2', part: "Inattention Symptoms", group: "4. No follow through", q: "Do you often leave things half done and start another project?" },
        { id: 'a4_3', part: "Inattention Symptoms", group: "4. No follow through", q: "Do you need consequences (such as deadlines) to finish?" },
        { id: 'a4_4', part: "Inattention Symptoms", group: "4. No follow through", q: "Do you have trouble following complex instructions?" },
        { id: 'a4_5', part: "Inattention Symptoms", group: "4. No follow through", q: "Do you need to write down instructions, otherwise you will forget them?" },
        { id: 'a5_1', part: "Inattention Symptoms", group: "5. Can't organize", q: "Do you have trouble organizing tasks into ordered steps?" },
        { id: 'a5_2', part: "Inattention Symptoms", group: "5. Can't organize", q: "Is it hard prioritizing work and chores?" },
        { id: 'a5_3', part: "Inattention Symptoms", group: "5. Can't organize", q: "Do you need others to plan for you?" },
        { id: 'a5_4', part: "Inattention Symptoms", group: "5. Can't organize", q: "Do you have trouble with time management?" },
        { id: 'a5_5', part: "Inattention Symptoms", group: "5. Can't organize", q: "Does difficulty in planning lead to procrastination?" },
        { id: 'a6_1', part: "Inattention Symptoms", group: "6. Avoids sustained effort", q: "Do you avoid tasks (work, chores, reading) that are challenging or lengthy?" },
        { id: 'a6_2', part: "Inattention Symptoms", group: "6. Avoids sustained effort", q: "Do you have to force yourself to do these tasks?" },
        { id: 'a6_3', part: "Inattention Symptoms", group: "6. Avoids sustained effort", q: "Do you procrastinate and put off tasks until the last moment possible?" },
        { id: 'a7_1', part: "Inattention Symptoms", group: "7. Loses important items", q: "Do you lose things (eg, important work papers, keys, wallet, coats)?" },
        { id: 'a7_2', part: "Inattention Symptoms", group: "7. Loses important items", q: "Are you constantly looking for important items?" },
        { id: 'a7_3', part: "Inattention Symptoms", group: "7. Loses important items", q: "Do you get into trouble for this?" },
        { id: 'a7_4', part: "Inattention Symptoms", group: "7. Loses important items", q: "Do you need to put items in the same place each time to avoid losing them?" },
        { id: 'a8_1', part: "Inattention Symptoms", group: "8. Easily distractible", q: "Are you ever very easily distracted by events around you (noise, movement, clutter)?" },
        { id: 'a8_2', part: "Inattention Symptoms", group: "8. Easily distractible", q: "Do you need relative isolation to get work done?" },
        { id: 'a8_3', part: "Inattention Symptoms", group: "8. Easily distractible", q: "Can almost anything get your mind off of what you are doing?" },
        { id: 'a8_4', part: "Inattention Symptoms", group: "8. Easily distractible", q: "Is it hard to get back to a task once you stop?" },
        { id: 'a9_1', part: "Inattention Symptoms", group: "9. Forgetful in daily activities", q: "Do you forget a lot of things in your daily routine (chores, work, appointments)?" },
        { id: 'a9_2', part: "Inattention Symptoms", group: "9. Forgetful in daily activities", q: "Do you forget to bring things to work?" },
        { id: 'a9_3', part: "Inattention Symptoms", group: "9. Forgetful in daily activities", q: "Do you need to write regular reminders, otherwise you will forget?" },
        { id: 'a10_1', part: "Hyperactivity-Impulsivity", group: "10. Squirms and fidgets", q: "Can you sit still or are you always moving your hands or feet?" },
        { id: 'a10_2', part: "Hyperactivity-Impulsivity", group: "10. Squirms and fidgets", q: "Do you tap your pencil or your feet?" },
        { id: 'a10_3', part: "Hyperactivity-Impulsivity", group: "10. Squirms and fidgets", q: "Do you regularly play with your hair or clothing?" },
        { id: 'a10_4', part: "Hyperactivity-Impulsivity", group: "10. Squirms and fidgets", q: "Do you consciously resist fidgeting or squirming?" },
        { id: 'a11_1', part: "Hyperactivity-Impulsivity", group: "11. Can't stay seated", q: "Do you have trouble staying in your seat (work, class, home)?" },
        { id: 'a11_2', part: "Hyperactivity-Impulsivity", group: "11. Can't stay seated", q: "Do you choose to walk around rather than sit?" },
        { id: 'a11_3', part: "Hyperactivity-Impulsivity", group: "11. Can't stay seated", q: "Do you have to force yourself to remain seated?" },
        { id: 'a11_4', part: "Hyperactivity-Impulsivity", group: "11. Can't stay seated", q: "Is it difficult for you to sit through a long meeting or lecture?" },
        { id: 'a11_5', part: "Hyperactivity-Impulsivity", group: "11. Can't stay seated", q: "Do you try to avoid going to functions that require you to sit still?" },
        { id: 'a12_1', part: "Hyperactivity-Impulsivity", group: "12. Runs/climbs excessively", q: "Are you physically restless?" },
        { id: 'a12_2', part: "Hyperactivity-Impulsivity", group: "12. Runs/climbs excessively", q: "Do you feel restless inside?" },
        { id: 'a12_3', part: "Hyperactivity-Impulsivity", group: "12. Runs/climbs excessively", q: "Do you feel more agitated when you cannot exercise daily?" },
        { id: 'a13_1', part: "Hyperactivity-Impulsivity", group: "13. Can't play/work quietly", q: "Do you have a hard time playing/working quietly?" },
        { id: 'a13_2', part: "Hyperactivity-Impulsivity", group: "13. Can't play/work quietly", q: "During leisure activity, are you agitated or dysphoric?" },
        { id: 'a13_3', part: "Hyperactivity-Impulsivity", group: "13. Can't play/work quietly", q: "Do you always need to be busy after work or while on vacation?" },
        { id: 'a14_1', part: "Hyperactivity-Impulsivity", group: "14. Driven by a motor", q: "Is it hard for you to slow down?" },
        { id: 'a14_2', part: "Hyperactivity-Impulsivity", group: "14. Driven by a motor", q: "Do you feel like you (often) have a lot of energy and always have to be moving?" },
        { id: 'a14_3', part: "Hyperactivity-Impulsivity", group: "14. Driven by a motor", q: "Do you feel like you're driven by a motor?" },
        { id: 'a14_4', part: "Hyperactivity-Impulsivity", group: "14. Driven by a motor", q: "Do you feel unable to relax?" },
        { id: 'a15_1', part: "Hyperactivity-Impulsivity", group: "15. Talks excessively", q: "Do you talk a lot? All the time?" },
        { id: 'a15_2', part: "Hyperactivity-Impulsivity", group: "15. Talks excessively", q: "Do people complain about your talking?" },
        { id: 'a15_3', part: "Hyperactivity-Impulsivity", group: "15. Talks excessively", q: "Are you often louder than the people you are talking to?" },
        { id: 'a16_1', part: "Hyperactivity-Impulsivity", group: "16. Blurts out answers", q: "Do you give answers to questions before someone finishes asking?" },
        { id: 'a16_2', part: "Hyperactivity-Impulsivity", group: "16. Blurts out answers", q: "Do you say things before it is your turn?" },
        { id: 'a16_3', part: "Hyperactivity-Impulsivity", group: "16. Blurts out answers", q: "Do you say things that don't fit into the conversation?" },
        { id: 'a16_4', part: "Hyperactivity-Impulsivity", group: "16. Blurts out answers", q: "Do you do things without thinking?" },
        { id: 'a17_1', part: "Hyperactivity-Impulsivity", group: "17. Can't wait for turn", q: "Is it hard for you to wait your turn (lines, driving)?" },
        { id: 'a17_2', part: "Hyperactivity-Impulsivity", group: "17. Can't wait for turn", q: "Are you frequently frustrated with delays?" },
        { id: 'a17_3', part: "Hyperactivity-Impulsivity", group: "17. Can't wait for turn", q: "Do you plan to avoid situations where you have to wait?" },
        { id: 'a18_1', part: "Hyperactivity-Impulsivity", group: "18. Intrudes/interrupts", q: "Do you talk when others are talking, without waiting?" },
        { id: 'a18_2', part: "Hyperactivity-Impulsivity", group: "18. Intrudes/interrupts", q: "Do you butt into others' conversations?" },
        { id: 'a18_3', part: "Hyperactivity-Impulsivity", group: "18. Intrudes/interrupts", q: "Do you interrupt others' activities?" },
        { id: 'a18_4', part: "Hyperactivity-Impulsivity", group: "18. Intrudes/interrupts", q: "Is it hard for you to wait to get your point across?" }
    ],
    wurs: [
        { id: 'w1', part: "Childhood Behaviors", group: "General Behavior", q: "1. Active, restless, always on the go" },
        { id: 'w2', part: "Childhood Behaviors", group: "General Behavior", q: "2. Afraid of things" },
        { id: 'w3', part: "Childhood Behaviors", group: "General Behavior", q: "3. Concentration problems, easily distracted" },
        { id: 'w4', part: "Childhood Behaviors", group: "General Behavior", q: "4. Anxious, worrying" },
        { id: 'w5', part: "Childhood Behaviors", group: "General Behavior", q: "5. Nervous, fidgety" },
        { id: 'w6', part: "Childhood Behaviors", group: "General Behavior", q: "6. Inattentive, daydreaming" },
        { id: 'w7', part: "Childhood Behaviors", group: "General Behavior", q: "7. Hot- or short-tempered, low boiling point" },
        { id: 'w8', part: "Childhood Behaviors", group: "General Behavior", q: "8. Shy, sensitive" },
        { id: 'w9', part: "Childhood Behaviors", group: "General Behavior", q: "9. Temper outbursts, tantrums" },
        { id: 'w10', part: "Childhood Behaviors", group: "General Behavior", q: "10. Trouble with stick-to-it-tiveness, not following through. Failing to finish things started" },
        { id: 'w11', part: "Childhood Behaviors", group: "General Behavior", q: "11. Stubborn, strong-willed" },
        { id: 'w12', part: "Childhood Behaviors", group: "General Behavior", q: "12. Sad or blue, depressed, unhappy" },
        { id: 'w13', part: "Childhood Behaviors", group: "General Behavior", q: "13. Incautious, dare-devilish, involved in pranks" },
        { id: 'w14', part: "Childhood Behaviors", group: "General Behavior", q: "14. Not getting a kick out of things, dissatisfied with life" },
        { id: 'w15', part: "Childhood Behaviors", group: "General Behavior", q: "15. Disobedient with parents, rebellious, sassy" },
        { id: 'w16', part: "Childhood Behaviors", group: "General Behavior", q: "16. Low opinion of myself" },
        { id: 'w17', part: "Childhood Behaviors", group: "General Behavior", q: "17. Irritable" },
        { id: 'w18', part: "Childhood Behaviors", group: "General Behavior", q: "18. Outgoing, friendly, enjoyed company of people" },
        { id: 'w19', part: "Childhood Behaviors", group: "General Behavior", q: "19. Sloppy, disorganized" },
        { id: 'w20', part: "Childhood Behaviors", group: "General Behavior", q: "20. Moody, ups and downs" },
        { id: 'w21', part: "Childhood Behaviors", group: "General Behavior", q: "21. Angry" },
        { id: 'w22', part: "Childhood Behaviors", group: "General Behavior", q: "22. Friends, popular" },
        { id: 'w23', part: "Childhood Behaviors", group: "General Behavior", q: "23. Well-organized, tidy, neat" },
        { id: 'w24', part: "Childhood Behaviors", group: "General Behavior", q: "24. Acting without thinking, impulsive" },
        { id: 'w25', part: "Childhood Behaviors", group: "General Behavior", q: "25. Tendency to be immature" },
        { id: 'w26', part: "Childhood Behaviors", group: "General Behavior", q: "26. Guilty feelings, regretful" },
        { id: 'w27', part: "Childhood Behaviors", group: "General Behavior", q: "27. Losing control of myself" },
        { id: 'w28', part: "Childhood Behaviors", group: "General Behavior", q: "28. Tendency to be or act irrational" },
        { id: 'w29', part: "Childhood Behaviors", group: "General Behavior", q: "29. Unpopular with other children, didn't keep friends for long, didn't get along with other children" },
        { id: 'w30', part: "Childhood Behaviors", group: "General Behavior", q: "30. Poorly coordinated, did not participate in sports" },
        { id: 'w31', part: "Childhood Behaviors", group: "General Behavior", q: "31. Afraid of losing control of self" },
        { id: 'w32', part: "Childhood Behaviors", group: "General Behavior", q: "32. Well-coordinated, picked first in games" },
        { id: 'w33', part: "Childhood Behaviors", group: "General Behavior", q: "33. Tomboyish (for women only)" },
        { id: 'w34', part: "Childhood Behaviors", group: "General Behavior", q: "34. Running away from home" },
        { id: 'w35', part: "Childhood Behaviors", group: "General Behavior", q: "35. Getting into fights" },
        { id: 'w36', part: "Childhood Behaviors", group: "General Behavior", q: "36. Teasing other children" },
        { id: 'w37', part: "Childhood Behaviors", group: "General Behavior", q: "37. Leader, bossy" },
        { id: 'w38', part: "Childhood Behaviors", group: "General Behavior", q: "38. Difficulty getting awake" },
        { id: 'w39', part: "Childhood Behaviors", group: "General Behavior", q: "39. Follower, led around too much" },
        { id: 'w40', part: "Childhood Behaviors", group: "General Behavior", q: "40. Trouble seeing things from someone else's point of view" },
        { id: 'w41', part: "Childhood Behaviors", group: "General Behavior", q: "41. Trouble with authorities, trouble with school, visits to principal's office" },
        { id: 'w42', part: "Childhood Behaviors", group: "General Behavior", q: "42. Trouble with police, booked convicted" },
        { id: 'w43', part: "Medical Problems", group: "Medical", q: "43. Headaches" },
        { id: 'w44', part: "Medical Problems", group: "Medical", q: "44. Stomachaches" },
        { id: 'w45', part: "Medical Problems", group: "Medical", q: "45. Constipation" },
        { id: 'w46', part: "Medical Problems", group: "Medical", q: "46. Diarrhea" },
        { id: 'w47', part: "Medical Problems", group: "Medical", q: "47. Food allergies" },
        { id: 'w48', part: "Medical Problems", group: "Medical", q: "48. Other allergies" },
        { id: 'w49', part: "Medical Problems", group: "Medical", q: "49. Bedwetting" },
        { id: 'w50', part: "School Experience", group: "School", q: "50. Overall a good student, fast" },
        { id: 'w51', part: "School Experience", group: "School", q: "51. Overall a poor student, slow learner" },
        { id: 'w52', part: "School Experience", group: "School", q: "52. Slow in learning to read" },
        { id: 'w53', part: "School Experience", group: "School", q: "53. Slow reader" },
        { id: 'w54', part: "School Experience", group: "School", q: "54. Trouble reversing letters" },
        { id: 'w55', part: "School Experience", group: "School", q: "55. Problems with spelling" },
        { id: 'w56', part: "School Experience", group: "School", q: "56. Trouble with mathematics or numbers" },
        { id: 'w57', part: "School Experience", group: "School", q: "57. Bad handwriting" },
        { id: 'w58', part: "School Experience", group: "School", q: "58. Able to read pretty well but never really enjoyed reading" },
        { id: 'w59', part: "School Experience", group: "School", q: "59. Not achieving up to potential" },
        { id: 'w60', part: "School Experience", group: "School", q: "60. Repeating grades" },
        { id: 'w61', part: "School Experience", group: "School", q: "61. Suspended or expelled" }
    ],
    aq: [
        // SOCIAL SKILL - Items about social interactions and friendships
        { id: 'aq1', group: "Social Skill", q: "1. I prefer to do things with others rather than on my own" },
        { id: 'aq11', group: "Social Skill", q: "11. I find social situations easy" },
        { id: 'aq13', group: "Social Skill", q: "13. I would rather go to a library than a party" },
        { id: 'aq15', group: "Social Skill", q: "15. I find myself drawn more strongly to people than to things" },
        { id: 'aq22', group: "Social Skill", q: "22. I find it hard to make new friends" },
        { id: 'aq36', group: "Social Skill", q: "36. I find it easy to work out what someone is thinking or feeling just by looking at their face" },
        { id: 'aq44', group: "Social Skill", q: "44. I enjoy social occasions" },
        { id: 'aq45', group: "Social Skill", q: "45. I find it difficult to work out people's intentions" },
        { id: 'aq47', group: "Social Skill", q: "47. I enjoy meeting new people" },
        { id: 'aq48', group: "Social Skill", q: "48. I am a good diplomat" },

        // ATTENTION SWITCHING - Items about flexibility and change
        { id: 'aq2', group: "Attention Switching", q: "2. I prefer to do things the same way over and over again" },
        { id: 'aq4', group: "Attention Switching", q: "4. I frequently get so strongly absorbed in one thing that I lose sight of other things" },
        { id: 'aq10', group: "Attention Switching", q: "10. In a social group, I can easily keep track of several different people's conversations" },
        { id: 'aq16', group: "Attention Switching", q: "16. I tend to have very strong interests, which I get upset about if I can't pursue" },
        { id: 'aq25', group: "Attention Switching", q: "25. It does not upset me if my daily routine is disturbed" },
        { id: 'aq32', group: "Attention Switching", q: "32. I find it easy to do more than one thing at once" },
        { id: 'aq34', group: "Attention Switching", q: "34. I enjoy doing things spontaneously" },
        { id: 'aq37', group: "Attention Switching", q: "37. If there is an interruption, I can switch back to what I was doing very quickly" },
        { id: 'aq43', group: "Attention Switching", q: "43. I like to plan any activities I participate in carefully" },
        { id: 'aq46', group: "Attention Switching", q: "46. New situations make me anxious" },

        // ATTENTION TO DETAIL - Items about noticing patterns and details
        { id: 'aq5', group: "Attention to Detail", q: "5. I often notice small sounds when others do not" },
        { id: 'aq6', group: "Attention to Detail", q: "6. I usually notice car number plates or similar strings of information" },
        { id: 'aq9', group: "Attention to Detail", q: "9. I am fascinated by dates" },
        { id: 'aq12', group: "Attention to Detail", q: "12. I tend to notice details that others do not" },
        { id: 'aq19', group: "Attention to Detail", q: "19. I am fascinated by numbers" },
        { id: 'aq23', group: "Attention to Detail", q: "23. I notice patterns in things all the time" },
        { id: 'aq28', group: "Attention to Detail", q: "28. I usually concentrate more on the whole picture, rather than the small details" },
        { id: 'aq29', group: "Attention to Detail", q: "29. I am not very good at remembering phone numbers" },
        { id: 'aq30', group: "Attention to Detail", q: "30. I don't usually notice small changes in a situation, or a person's appearance" },
        { id: 'aq49', group: "Attention to Detail", q: "49. I am not very good at remembering people's date of birth" },

        // COMMUNICATION - Items about conversation and understanding others
        { id: 'aq7', group: "Communication", q: "7. Other people frequently tell me that what I've said is impolite, even though I think it is polite" },
        { id: 'aq17', group: "Communication", q: "17. I enjoy social chit-chat" },
        { id: 'aq18', group: "Communication", q: "18. When I talk, it isn't always easy for others to get a word in edgeways" },
        { id: 'aq26', group: "Communication", q: "26. I frequently find that I don't know how to keep a conversation going" },
        { id: 'aq27', group: "Communication", q: "27. I find it easy to 'read between the lines' when someone is talking to me" },
        { id: 'aq31', group: "Communication", q: "31. I know how to tell if someone listening to me is getting bored" },
        { id: 'aq33', group: "Communication", q: "33. When I talk on the phone, I'm not sure when it's my turn to speak" },
        { id: 'aq35', group: "Communication", q: "35. I am often the last to understand the point of a joke" },
        { id: 'aq38', group: "Communication", q: "38. I am good at social chit-chat" },
        { id: 'aq39', group: "Communication", q: "39. People often tell me that I keep going on and on about the same thing" },

        // IMAGINATION - Items about pretending, creativity, and fiction
        { id: 'aq3', group: "Imagination", q: "3. If I try to imagine something, I find it very easy to create a picture in my mind" },
        { id: 'aq8', group: "Imagination", q: "8. When I'm reading a story, I can easily imagine what the characters might look like" },
        { id: 'aq14', group: "Imagination", q: "14. I find making up stories easy" },
        { id: 'aq20', group: "Imagination", q: "20. When I'm reading a story, I find it difficult to work out the characters' intentions." },
        { id: 'aq21', group: "Imagination", q: "21. I don't particularly enjoy reading fiction" },
        { id: 'aq24', group: "Imagination", q: "24. I would rather go to the theatre than a museum" },
        { id: 'aq40', group: "Imagination", q: "40. When I was young, I used to enjoy playing games involving pretending with other children" },
        { id: 'aq41', group: "Imagination", q: "41. I like to collect information about categories of things (e.g. types of car, types of bird, types of train, types of plant, etc.)" },
        { id: 'aq42', group: "Imagination", q: "42. I find it difficult to imagine what it would be like to be someone else" },
        { id: 'aq50', group: "Imagination", q: "50. I find it very easy to play games with children that involve pretending" }
    ],
    sasi: [],  // Will be loaded from sasi_questions.js
    aspie: []  // Will be loaded from aspie_questions.js
};
