// SASI Questions - Women's Symptom Inventory
QUESTIONS.sasi = [
    // PART I: CHILDHOOD AD/HD PATTERNS
    { id: 's_c_in_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Inattention", q: "1. I daydreamed a lot in school." },
    { id: 's_c_in_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Inattention", q: "2. My mind wandered, even when I tried to listen to the teacher." },
    { id: 's_c_in_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Inattention", q: "3. In class, I didn't hear the teacher's instructions." },
    { id: 's_c_in_4', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Inattention", q: "4. I made careless mistakes on tests." },
    { id: 's_c_in_5', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Inattention", q: "5. I often lost or misplaced things." },
    { id: 's_c_in_6', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Inattention", q: "6. I got teased for being 'spacey.'" },
    { id: 's_c_hy_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Hyperactivity", q: "1. I got in trouble for talking in class." },
    { id: 's_c_hy_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Hyperactivity", q: "2. I was a tomboy." },
    { id: 's_c_hy_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Hyperactivity", q: "3. It was hard for me to sit still in class." },
    { id: 's_c_hy_4', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Hyperactivity", q: "4. I felt best when I was moving around – playing sports or dancing." },
    { id: 's_c_hy_5', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Hyperactivity", q: "5. It was hard to fall asleep at bedtime because thoughts were bouncing around in my brain." },
    { id: 's_c_hy_6', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Hyperactivity", q: "6. I often doodled or fidgeted when I had to sit still." },
    { id: 's_c_hy_7', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Hyperactivity", q: "7. My friends called me 'hyper.'" },
    { id: 's_c_hy_8', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Hyperactivity", q: "8. When sitting, I tended to 'tip' my chair or jiggle my legs." },
    { id: 's_c_im_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Impulsivity", q: "1. I interrupted others, even though I tried not to." },
    { id: 's_c_im_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Impulsivity", q: "2. Sometimes, when I was upset, I'd blurt out things that I didn't mean." },
    { id: 's_c_im_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Impulsivity", q: "3. I acted silly or 'crazy' with my friends." },
    { id: 's_c_im_4', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Impulsivity", q: "4. I acted on the spur of the moment, never thinking of the trouble I'd get into." },
    { id: 's_c_im_5', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Impulsivity", q: "5. As a teenager, I sometimes drove too fast, or took other risks while driving." },
    { id: 's_c_pr_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Productivity", q: "1. In school, I didn't finish seatwork quickly as the rest of the class." },
    { id: 's_c_pr_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Productivity", q: "2. The demands of high school felt overwhelming sometimes." },
    { id: 's_c_pr_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Productivity", q: "3. I had to work much harder and stay up later than others to do well in school." },
    { id: 's_c_pr_4', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Productivity", q: "4. I studied or did homework late into the night." },
    { id: 's_c_ini_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Problems with initiation", q: "1. I had trouble getting started on my homework." },
    { id: 's_c_ini_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Problems with initiation", q: "2. It was hard for me to begin working on a project unless someone was there to keep me on track." },
    { id: 's_c_ini_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Problems with initiation", q: "3. I worked better with others than when I worked alone." },
    { id: 's_c_ft_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Problems with follow-through", q: "1. It was hard for me to complete long-term school projects." },
    { id: 's_c_ft_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Problems with follow-through", q: "2. I dabbled in many hobbies or activities, but never really persevered in my efforts." },
    { id: 's_c_ft_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Problems with follow-through", q: "3. Although I took different types of lessons as a child, I rarely or never practiced." },
    { id: 's_c_ua_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Problems with underarousal", q: "1. I felt sleepy when sitting in class, but felt energetic as soon as I stood up and moved." },
    { id: 's_c_ua_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Problems with underarousal", q: "2. It was difficult to get up in the morning." },
    { id: 's_c_ua_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Problems with underarousal", q: "3. I wasn't alert until late in the morning." },
    { id: 's_c_ua_4', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Problems with underarousal", q: "4. I didn't seem to have as much energy as most of my friends." },
    { id: 's_c_proc_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Procrastination problems", q: "1. I was smart, but got by doing everything at the last minute." },
    { id: 's_c_proc_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Procrastination problems", q: "2. I handed in my homework late, if I did it at all." },
    { id: 's_c_proc_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Procrastination problems", q: "3. The only way I could really study for a test was to stay up very late the night before." },
    { id: 's_c_lm_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Low motivation/underachievement", q: "1. I didn't do as well in school as I felt I should have." },
    { id: 's_c_lm_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Low motivation/underachievement", q: "2. I got by on my intelligence, and didn't really try hard in school." },
    { id: 's_c_lm_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Low motivation/underachievement", q: "3. My parents and teachers told me I could do much better if I tried." },
    { id: 's_c_lm_4', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Low motivation/underachievement", q: "4. I started each grading period with good intentions, but could never sustain them." },
    { id: 's_c_org_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Organizational difficulties", q: "1. My room looked like a 'disaster' area." },
    { id: 's_c_org_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Organizational difficulties", q: "2. My backpack/book bag/desk was messy." },
    { id: 's_c_org_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Organizational difficulties", q: "3. I had trouble being organized." },
    { id: 's_c_org_4', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Organizational difficulties", q: "4. I had trouble keeping track of assignments, long-term projects, and due dates." },
    { id: 's_c_tm_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Poor time management", q: "1. I arrived late for scheduled activities." },
    { id: 's_c_tm_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Poor time management", q: "2. I often lost track of time." },
    { id: 's_c_tm_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Poor time management", q: "3. I stayed up late, then had trouble getting up in the morning." },
    { id: 's_c_mot_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Problems with fine/gross motor control", q: "1. My handwriting was messy." },
    { id: 's_c_mot_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Problems with fine/gross motor control", q: "2. I was physically awkward and did poorly in sports." },
    { id: 's_c_mot_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "Problems with fine/gross motor control", q: "3. I tended to bump into things – corners of tables, door frames, etc." },
    { id: 's_c_lr_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "LEARNING ISSUES: Reading", q: "1. I was a slow reader." },
    { id: 's_c_lr_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "LEARNING ISSUES: Reading", q: "2. When reading, my mind wandered." },
    { id: 's_c_lr_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "LEARNING ISSUES: Reading", q: "3. Typically, after reading a textbook, I could not answer the questions at the end of the chapter." },
    { id: 's_c_lr_4', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "LEARNING ISSUES: Reading", q: "4. I needed to reread information to be sure that I understand it." },
    { id: 's_c_lr_5', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "LEARNING ISSUES: Reading", q: "5. I didn't read for pleasure." },
    { id: 's_c_lw_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "LEARNING ISSUES: Writing", q: "1. Writing assignments were difficult for me." },
    { id: 's_c_lw_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "LEARNING ISSUES: Writing", q: "2. I had lots of ideas, but couldn't organize them well when writing." },
    { id: 's_c_lw_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "LEARNING ISSUES: Writing", q: "3. I could explain what I knew verbally, but just couldn't get it down on paper." },
    { id: 's_c_lmem_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "LEARNING ISSUES: Memory", q: "1. I had trouble remembering the directions for assignments." },
    { id: 's_c_lmem_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "LEARNING ISSUES: Memory", q: "2. Even when I studied, I couldn't recall the information on a test." },
    { id: 's_c_lmem_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "LEARNING ISSUES: Memory", q: "3. I was forgetful and absentminded." },
    { id: 's_c_soc_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "SOCIAL/INTERPERSONAL: Shyness", q: "1. I felt shy and self-conscious around my classmates." },
    { id: 's_c_soc_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "SOCIAL/INTERPERSONAL: Shyness", q: "2. Even when I had something to say, I rarely raised my hand to volunteer in class." },
    { id: 's_c_soc_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "SOCIAL/INTERPERSONAL: Shyness", q: "3. I had only a few friends during school years." },
    { id: 's_c_soc_4', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "SOCIAL/INTERPERSONAL: Shyness", q: "4. I didn't date or rarely dated in high school." },
    { id: 's_c_int_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "SOCIAL/INTERPERSONAL: Interpersonal", q: "1. Other girls called me 'mean' or 'bossy.'" },
    { id: 's_c_int_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "SOCIAL/INTERPERSONAL: Interpersonal", q: "2. I felt different from other girls." },
    { id: 's_c_int_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "SOCIAL/INTERPERSONAL: Interpersonal", q: "3. Other girls didn't like me, but I didn't understand why." },
    { id: 's_c_int_4', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "SOCIAL/INTERPERSONAL: Interpersonal", q: "4. It was hard for me to keep up with the conversation of a group of girls." },
    { id: 's_c_int_5', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "SOCIAL/INTERPERSONAL: Interpersonal", q: "5. I fought and argued with my friends." },
    { id: 's_c_int_6', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "SOCIAL/INTERPERSONAL: Interpersonal", q: "6. In conversation, I'd say something dumb or couldn't think of anything to say." },
    { id: 's_c_int_7', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "SOCIAL/INTERPERSONAL: Interpersonal", q: "7. I was very sensitive to teasing." },
    { id: 's_c_psy_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PSYCHOLOGICAL: Moodiness", q: "1. I felt worried and anxious." },
    { id: 's_c_psy_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PSYCHOLOGICAL: Moodiness", q: "2. I felt moody and depressed for no reason." },
    { id: 's_c_psy_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PSYCHOLOGICAL: Moodiness", q: "3. I dreaded being called on by the teacher." },
    { id: 's_c_psy_4', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PSYCHOLOGICAL: Moodiness", q: "4. I didn't like going to school." },
    { id: 's_c_psy_5', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PSYCHOLOGICAL: Moodiness", q: "5. I became very anxious before tests." },
    { id: 's_c_psy_6', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PSYCHOLOGICAL: Moodiness", q: "6. I was irritable as a teenager." },
    { id: 's_c_psy_7', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PSYCHOLOGICAL: Moodiness", q: "7. I cried easily." },
    { id: 's_c_crit_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PSYCHOLOGICAL: Feeling Criticized", q: "1. I wish my parents had understood how hard high school was for me." },
    { id: 's_c_crit_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PSYCHOLOGICAL: Feeling Criticized", q: "2. It felt as if my parents criticized me a lot." },
    { id: 's_c_crit_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PSYCHOLOGICAL: Feeling Criticized", q: "3. My mother and I were in conflict during my high school years." },
    { id: 's_c_crit_4', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PSYCHOLOGICAL: Feeling Criticized", q: "4. I was repeatedly humiliated or criticized by teachers in the school setting." },
    { id: 's_c_se_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PSYCHOLOGICAL: Low Self-Esteem", q: "1. I feel a sense of shame or regret, as I look back on things I did in high school." },
    { id: 's_c_se_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PSYCHOLOGICAL: Low Self-Esteem", q: "2. I wasn't really good at anything." },
    { id: 's_c_se_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PSYCHOLOGICAL: Low Self-Esteem", q: "3. I didn't feel good about myself during my school years." },
    { id: 's_c_pb_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PROBLEMATIC BEHAVIORS: Impatience", q: "1. I was impatient and easily frustrated." },
    { id: 's_c_pb_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PROBLEMATIC BEHAVIORS: Impatience", q: "2. Although I controlled myself at school, I had screaming arguments at home with my family." },
    { id: 's_c_pb_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PROBLEMATIC BEHAVIORS: Impatience", q: "3. I quit a task if I encountered difficulty." },
    { id: 's_c_pb_4', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PROBLEMATIC BEHAVIORS: Impatience", q: "4. I lost my temper when frustrated." },
    { id: 's_c_rt_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PROBLEMATIC BEHAVIORS: Risk-taking", q: "1. I took risks when driving an automobile." },
    { id: 's_c_rt_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PROBLEMATIC BEHAVIORS: Risk-taking", q: "2. I started smoking at a younger age than many of my friends." },
    { id: 's_c_rt_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PROBLEMATIC BEHAVIORS: Risk-taking", q: "3. I was sexually active earlier than other girls." },
    { id: 's_c_rt_4', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PROBLEMATIC BEHAVIORS: Risk-taking", q: "4. I drank and experimented with drugs in high school or earlier." },
    { id: 's_c_rt_5', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PROBLEMATIC BEHAVIORS: Risk-taking", q: "5. I abused alcohol or other substances in high school or earlier." },
    { id: 's_c_odd_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PROBLEMATIC BEHAVIORS: Oppositional", q: "1. I got into trouble as a teenager." },
    { id: 's_c_odd_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PROBLEMATIC BEHAVIORS: Oppositional", q: "2. I rebelled against my parents." },
    { id: 's_c_odd_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PROBLEMATIC BEHAVIORS: Oppositional", q: "3. My parents didn't like the kids that I hung out with in high school." },
    { id: 's_c_odd_4', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PROBLEMATIC BEHAVIORS: Oppositional", q: "4. I skipped classes in high school." },
    { id: 's_c_odd_5', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PROBLEMATIC BEHAVIORS: Oppositional", q: "5. I fought with my parents over rules and curfew." },
    { id: 's_c_odd_6', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PROBLEMATIC BEHAVIORS: Oppositional", q: "6. My parents didn't approve of my boyfriend in high school." },
    { id: 's_c_odd_7', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PROBLEMATIC BEHAVIORS: Oppositional", q: "7. I was very argumentative." },
    { id: 's_c_odd_8', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PROBLEMATIC BEHAVIORS: Oppositional", q: "8. I couldn't take 'no' for an answer." },
    { id: 's_c_eat_1', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PROBLEMATIC BEHAVIORS: Eating", q: "1. I ate compulsively as a child or teen." },
    { id: 's_c_eat_2', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PROBLEMATIC BEHAVIORS: Eating", q: "2. I developed a pattern of bulimia." },
    { id: 's_c_eat_3', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PROBLEMATIC BEHAVIORS: Eating", q: "3. I became overweight after puberty." },
    { id: 's_c_eat_4', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PROBLEMATIC BEHAVIORS: Eating", q: "4. I repeatedly dieted without success." },
    { id: 's_c_eat_5', part: "PART I: CHILDHOOD AD/HD PATTERNS", group: "PROBLEMATIC BEHAVIORS: Eating", q: "5. I binged on certain foods until I felt stuffed, even sick." },

    // PART II: ADULT AD/HD PATTERNS  
    { id: 's_a_in_1', part: "PART II: ADULT AD/HD PATTERNS", group: "Inattention", q: "1. I tend to overlook details." },
    { id: 's_a_in_2', part: "PART II: ADULT AD/HD PATTERNS", group: "Inattention", q: "2. Forms are difficult for me to complete correctly without overlooking something." },
    { id: 's_a_in_3', part: "PART II: ADULT AD/HD PATTERNS", group: "Inattention", q: "3. It is hard for me to listen for long periods of time – in a lecture, seminar, or training class." },
    { id: 's_a_in_4', part: "PART II: ADULT AD/HD PATTERNS", group: "Inattention", q: "4. My mind tends to wander when I'm reading or when listening to something that is not interesting." },
    { id: 's_a_dis_1', part: "PART II: ADULT AD/HD PATTERNS", group: "Distractibility", q: "1. I am easily sidetracked, and wander from one task to the next as something catches my attention." },
    { id: 's_a_dis_2', part: "PART II: ADULT AD/HD PATTERNS", group: "Distractibility", q: "2. I jump from topic to topic in conversation, forgetting what I started to say." },
    { id: 's_a_dis_3', part: "PART II: ADULT AD/HD PATTERNS", group: "Distractibility", q: "3. I have difficulty concentrating when there is noise or conversation near me." },
    { id: 's_a_dis_4', part: "PART II: ADULT AD/HD PATTERNS", group: "Distractibility", q: "4. It is very difficult for me to get back on track after an interruption." },
    { id: 's_a_hyp_1', part: "PART II: ADULT AD/HD PATTERNS", group: "Tendency to hyperfocus", q: "1. I tend to 'hyperfocus' for long periods of time on certain activities." },
    { id: 's_a_hyp_2', part: "PART II: ADULT AD/HD PATTERNS", group: "Tendency to hyperfocus", q: "2. When engaging in certain activities, I completely lose track of time." },
    { id: 's_a_hyp_3', part: "PART II: ADULT AD/HD PATTERNS", group: "Tendency to hyperfocus", q: "3. When I'm really concentrating, I don't hear what people say to me." },
    { id: 's_a_trans_1', part: "PART II: ADULT AD/HD PATTERNS", group: "Difficulty making transitions", q: "1. It is difficult for me to stop an activity when it is time to do something else." },
    { id: 's_a_trans_2', part: "PART II: ADULT AD/HD PATTERNS", group: "Difficulty making transitions", q: "2. I can't tear myself away from an activity when I'm really engrossed." },
    { id: 's_a_h_1', part: "PART II: ADULT AD/HD PATTERNS", group: "Hyperactivity", q: "1. I tend to fidget or doodle." },
    { id: 's_a_h_2', part: "PART II: ADULT AD/HD PATTERNS", group: "Hyperactivity", q: "2. I talk so fast that others 'can't get a word in.'" },
    { id: 's_a_h_3', part: "PART II: ADULT AD/HD PATTERNS", group: "Hyperactivity", q: "3. I hate to sit for long periods, and find an excuse to move around." },
    { id: 's_a_h_4', part: "PART II: ADULT AD/HD PATTERNS", group: "Hyperactivity", q: "4. I seem to need less sleep than other women." },
    { id: 's_a_h_5', part: "PART II: ADULT AD/HD PATTERNS", group: "Hyperactivity", q: "5. I have a high energy level compared to many women." },
    { id: 's_a_h_6', part: "PART II: ADULT AD/HD PATTERNS", group: "Hyperactivity", q: "6. My activity level makes the people around me uncomfortable." },
    { id: 's_a_imp_1', part: "PART II: ADULT AD/HD PATTERNS", group: "Impulsivity", q: "1. I buy on impulse." },
    { id: 's_a_imp_2', part: "PART II: ADULT AD/HD PATTERNS", group: "Impulsivity", q: "2. I interrupt others in conversation, even when I try not to." },
    { id: 's_a_imp_3', part: "PART II: ADULT AD/HD PATTERNS", group: "Impulsivity", q: "3. I have impulsively jumped from one job to another." },
    { id: 's_a_imp_4', part: "PART II: ADULT AD/HD PATTERNS", group: "Impulsivity", q: "4. I have impulsively quit a job without considering the consequences." },
    { id: 's_a_imp_5', part: "PART II: ADULT AD/HD PATTERNS", group: "Impulsivity", q: "5. I tend to 'blurt out' whatever I'm thinking; though I may later regret it." },
    { id: 's_a_imp_6', part: "PART II: ADULT AD/HD PATTERNS", group: "Impulsivity", q: "6. I have made major life decisions with little planning or forethought." },
    { id: 's_a_prod_1', part: "PART II: ADULT AD/HD PATTERNS", group: "Productivity", q: "1. I just can't seem to juggle the number of activities and commitments that my friends seem to manage." },
    { id: 's_a_prod_2', part: "PART II: ADULT AD/HD PATTERNS", group: "Productivity", q: "2. I have felt overwhelmed by responsibilities at certain times in my life." },
    { id: 's_a_prod_3', part: "PART II: ADULT AD/HD PATTERNS", group: "Productivity", q: "3. It seems much harder for me than for others to take care of the tasks of everyday tasks." },
    { id: 's_a_prod_4', part: "PART II: ADULT AD/HD PATTERNS", group: "Productivity", q: "4. Keeping up with job demands has been difficult for me." },
    { id: 's_a_init_1', part: "PART II: ADULT AD/HD PATTERNS", group: "Problems with initiation", q: "1. Despite my best intentions, it is often hard for me to get started on a project." },
    { id: 's_a_init_2', part: "PART II: ADULT AD/HD PATTERNS", group: "Problems with initiation", q: "2. Getting started is much easier when I work with someone else." },
    { id: 's_a_ft_1', part: "PART II: ADULT AD/HD PATTERNS", group: "Problems with follow-through", q: "1. I tend not to finish doing laundry - it's always 'in progress.'" },
    { id: 's_a_ft_2', part: "PART II: ADULT AD/HD PATTERNS", group: "Problems with follow-through", q: "2. I have many unfinished projects that I intend to 'get around to.'" },
    { id: 's_a_ft_3', part: "PART II: ADULT AD/HD PATTERNS", group: "Problems with follow-through", q: "3. I pick up and drop hobbies or interests." },
    { id: 's_a_ft_4', part: "PART II: ADULT AD/HD PATTERNS", group: "Problems with follow-through", q: "4. I don't meet the long-term goals I set for myself." },
    { id: 's_a_dec_1', part: "PART II: ADULT AD/HD PATTERNS", group: "Problems making decisions", q: "1. I have difficulty deciding what to discard and what to keep." },
    { id: 's_a_dec_2', part: "PART II: ADULT AD/HD PATTERNS", group: "Problems making decisions", q: "2. I have difficulty making selections in large department or grocery stores." },
    { id: 's_a_dec_3', part: "PART II: ADULT AD/HD PATTERNS", group: "Problems making decisions", q: "3. Prioritizing is difficult for me – everything seems equally important." },
    { id: 's_a_plan_1', part: "PART II: ADULT AD/HD PATTERNS", group: "Difficulties in planning", q: "1. Meal planning is very difficult for me." },
    { id: 's_a_plan_2', part: "PART II: ADULT AD/HD PATTERNS", group: "Difficulties in planning", q: "2. I rarely plan my day and typically react to events as they occur." },
    { id: 's_a_plan_3', part: "PART II: ADULT AD/HD PATTERNS", group: "Difficulties in planning", q: "3. When doing a project, I figure it out as I go along." },
    { id: 's_a_plan_4', part: "PART II: ADULT AD/HD PATTERNS", group: "Difficulties in planning", q: "4. I have difficulty planning ahead." },
    { id: 's_a_plan_5', part: "PART II: ADULT AD/HD PATTERNS", group: "Difficulties in planning", q: "5. I rarely engage in social activities that require advance planning." },
    { id: 's_a_sens_1', part: "PART II: ADULT AD/HD PATTERNS", group: "Sensitivity to over-stimulation", q: "1. Loud noises irritate me." },
    { id: 's_a_sens_2', part: "PART II: ADULT AD/HD PATTERNS", group: "Sensitivity to over-stimulation", q: "2. I don't like to be in large crowds." },
    { id: 's_a_sens_3', part: "PART II: ADULT AD/HD PATTERNS", group: "Sensitivity to over-stimulation", q: "3. Shopping centers and large 'superstores' feel overwhelming to me." },
    { id: 's_a_sens_4', part: "PART II: ADULT AD/HD PATTERNS", group: "Sensitivity to over-stimulation", q: "4. Fluorescent lighting tends to bother me." },
    { id: 's_a_stim_1', part: "PART II: ADULT AD/HD PATTERNS", group: "Need for stimulation", q: "1. I am easily bored." },
    { id: 's_a_stim_2', part: "PART II: ADULT AD/HD PATTERNS", group: "Need for stimulation", q: "2. I enjoy new projects and dislike doing routine activities." },
    { id: 's_a_stim_3', part: "PART II: ADULT AD/HD PATTERNS", group: "Need for stimulation", q: "3. I have a wide range of interests and activities." },
    { id: 's_a_stim_4', part: "PART II: ADULT AD/HD PATTERNS", group: "Need for stimulation", q: "4. I enjoy making changes in my life." },
    { id: 's_a_stim_5', part: "PART II: ADULT AD/HD PATTERNS", group: "Need for stimulation", q: "5. I thrive on stimulation." },
    { id: 's_a_ua_1', part: "PART II: ADULT AD/HD PATTERNS", group: "Problems with under-arousal", q: "1. I am not fully awake and alert until several hours after I rise in the morning." },
    { id: 's_a_ua_2', part: "PART II: ADULT AD/HD PATTERNS", group: "Problems with under-arousal", q: "2. Getting up in the morning is usually difficult for me." },
    { id: 's_a_ua_3', part: "PART II: ADULT AD/HD PATTERNS", group: "Problems with under-arousal", q: "3. I use sugar and/or caffeine to keep myself going during the day." },
    { id: 's_a_ua_4', part: "PART II: ADULT AD/HD PATTERNS", group: "Problems with under-arousal", q: "4. If my life circumstances allowed it, I would take a daily afternoon nap." },
    { id: 's_a_ua_5', part: "PART II: ADULT AD/HD PATTERNS", group: "Problems with under-arousal", q: "5. On weekends, I sleep late or nap to catch up on my sleep." },
    { id: 's_a_proc_1', part: "PART II: ADULT AD/HD PATTERNS", group: "Procrastination", q: "1. I procrastinate and resist doing tasks that are difficult or unappealing." },
    { id: 's_a_proc_2', part: "PART II: ADULT AD/HD PATTERNS", group: "Procrastination", q: "2. I put things off until the last minute." },
    { id: 's_a_lm_1', part: "PART II: ADULT AD/HD PATTERNS", group: "Low motivation/self-discipline", q: "1. I tend to do what I like before what I 'ought.'" },
    { id: 's_a_lm_2', part: "PART II: ADULT AD/HD PATTERNS", group: "Low motivation/self-discipline", q: "2. I rarely stick with a goal or project that takes effort." },
    { id: 's_a_lm_3', part: "PART II: ADULT AD/HD PATTERNS", group: "Low motivation/self-discipline", q: "3. Many things seem like 'too much trouble' to me." },
    { id: 's_a_org_1', part: "PART II: ADULT AD/HD PATTERNS", group: "Organizational difficulties", q: "1. My home is cluttered and messy." },
    { id: 's_a_org_2', part: "PART II: ADULT AD/HD PATTERNS", group: "Organizational difficulties", q: "2. I keep things organized at work, but my personal life is a shambles." },
    { id: 's_a_org_3', part: "PART II: ADULT AD/HD PATTERNS", group: "Organizational difficulties", q: "3. I try to get organized, but I never seem to accomplish my goal." },
    { id: 's_a_org_4', part: "PART II: ADULT AD/HD PATTERNS", group: "Organizational difficulties", q: "4. I have difficulty organizing my thoughts when writing." },
    { id: 's_a_org_5', part: "PART II: ADULT AD/HD PATTERNS", group: "Organizational difficulties", q: "5. I can't seem to organize my paperwork – either at home or at work." },
    { id: 's_a_tm_1', part: "PART II: ADULT AD/HD PATTERNS", group: "Poor time management", q: "1. I tend to run late and end up feeling frantic." },
    { id: 's_a_tm_2', part: "PART II: ADULT AD/HD PATTERNS", group: "Poor time management", q: "2. I overcrowd my schedule and overcommit myself." },
    { id: 's_a_tm_3', part: "PART II: ADULT AD/HD PATTERNS", group: "Poor time management", q: "3. I run late because I try to squeeze in 'one last thing.'" },
    { id: 's_a_tm_4', part: "PART II: ADULT AD/HD PATTERNS", group: "Poor time management", q: "4. I dawdle and lose track of time." },
    { id: 's_a_tm_5', part: "PART II: ADULT AD/HD PATTERNS", group: "Poor time management", q: "5. I tend to underestimate how much time an activity will take." }
];
