// SASI Additional Parts - Continuing from sasi_questions.js
const SASI_ADDITIONAL = [
    // DIFFICULTIES RELATED TO LEARNING DISABILITIES
    { id: 's_ld_r_1', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Reading difficulties", q: "1. I was diagnosed with learning disabilities in school." },
    { id: 's_ld_r_2', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Reading difficulties", q: "2. I rarely read for pleasure." },
    { id: 's_ld_r_3', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Reading difficulties", q: "3. While reading, I can concentrate only if the material is very interesting to me." },
    { id: 's_ld_r_4', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Reading difficulties", q: "4. I have difficulty recalling information that I have read." },
    { id: 's_ld_r_5', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Reading difficulties", q: "5. I read slowly." },
    { id: 's_ld_r_6', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Reading difficulties", q: "6. I must reread text in order to fully comprehend it." },
    { id: 's_ld_w_1', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Writing difficulties", q: "1. Writing papers is difficult for me." },
    { id: 's_ld_w_2', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Writing difficulties", q: "2. I have difficulty organizing my thoughts in writing, even when I am very familiar with the subject." },
    { id: 's_ld_w_3', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Writing difficulties", q: "3. I am much more comfortable explaining something verbally than in writing." },
    { id: 's_ld_w_4', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Writing difficulties", q: "4. Difficulty with writing has caused problems for me at work." },
    { id: 's_ld_w_5', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Writing difficulties", q: "5. Spelling is difficult for me." },
    { id: 's_ld_w_6', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Writing difficulties", q: "6. Punctuation and grammar are difficult for me." },
    { id: 's_ld_m_1', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Memory problems", q: "1. I need to speak the moment I think of something in order not to forget my thought." },
    { id: 's_ld_m_2', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Memory problems", q: "2. I misplace personal belongings." },
    { id: 's_ld_m_3', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Memory problems", q: "3. I have difficulty recalling the names of common objects or others." },
    { id: 's_ld_m_4', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Memory problems", q: "4. I am absentminded." },
    { id: 's_ld_m_5', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Memory problems", q: "5. I have to write things down to remember them." },
    { id: 's_ld_m_6', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Memory problems", q: "6. I forget to do thing that I intend to do." },
    { id: 's_ld_m_7', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Memory problems", q: "7. I have difficulty remembering multi-step directions or multi-item lists." },
    { id: 's_ld_m_8', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Memory problems", q: "8. My recall is variable and unpredictable." },
    { id: 's_ld_mot_1', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Problems with motor control", q: "1. I have poor handwriting." },
    { id: 's_ld_mot_2', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Problems with motor control", q: "2. The legibility of my handwriting is variable." },
    { id: 's_ld_mot_3', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Problems with motor control", q: "3. I tend to bump into or trip over things." },
    { id: 's_ld_mot_4', part: "DIFFICULTIES RELATED TO LEARNING DISABILITIES", group: "Problems with motor control", q: "4. I have poor motor coordination." },
    // DIFFICULTIES IN AREAS OF ADULT RESPONSIBILITY
    { id: 's_ar_p_1', part: "DIFFICULTIES IN ADULT RESPONSIBILITY", group: "Parenting", q: "1. My parenting is inconsistent." },
    { id: 's_ar_p_2', part: "DIFFICULTIES IN ADULT RESPONSIBILITY", group: "Parenting", q: "2. I can't develop routines for myself, much less establish them for my child(ren)." },
    { id: 's_ar_p_3', part: "DIFFICULTIES IN ADULT RESPONSIBILITY", group: "Parenting", q: "3. I have difficulty not losing my temper with my child(ren)." },
    { id: 's_ar_w_1', part: "DIFFICULTIES IN ADULT RESPONSIBILITY", group: "Workplace", q: "1. I have received unsatisfactory performance ratings at work." },
    { id: 's_ar_w_2', part: "DIFFICULTIES IN ADULT RESPONSIBILITY", group: "Workplace", q: "2. I have quit a job in order to avoid being fired." },
    { id: 's_ar_w_3', part: "DIFFICULTIES IN ADULT RESPONSIBILITY", group: "Workplace", q: "3. I have changed jobs many times, never finding the 'right' job." },
    { id: 's_ar_life_1', part: "DIFFICULTIES IN ADULT RESPONSIBILITY", group: "Life maintenance", q: "1. I don't keep up with housekeeping tasks in a regular, consistent manner." },
    { id: 's_ar_life_2', part: "DIFFICULTIES IN ADULT RESPONSIBILITY", group: "Life maintenance", q: "2. My home/office are filled with disorganized piles of papers." },
    { id: 's_ar_life_3', part: "DIFFICULTIES IN ADULT RESPONSIBILITY", group: "Life maintenance", q: "3. My wardrobe is disorganized and in disarray." },
    { id: 's_ar_life_4', part: "DIFFICULTIES IN ADULT RESPONSIBILITY", group: "Life maintenance", q: "4. I typically neglect making routine medical/dental appointments." },
    { id: 's_ar_life_5', part: "DIFFICULTIES IN ADULT RESPONSIBILITY", group: "Life maintenance", q: "5. I neglect to take care of routine automobile maintenance." },
    { id: 's_ar_life_6', part: "DIFFICULTIES IN ADULT RESPONSIBILITY", group: "Life maintenance", q: "6. Laundry is done at the last possible moment." },
    { id: 's_ar_life_7', part: "DIFFICULTIES IN ADULT RESPONSIBILITY", group: "Life maintenance", q: "7. I wait until my car is nearly out of gas before filling the tank." },
    { id: 's_ar_life_8', part: "DIFFICULTIES IN ADULT RESPONSIBILITY", group: "Life maintenance", q: "8. My life is filled with numerous, avoidable crises." },
    { id: 's_ar_fin_1', part: "DIFFICULTIES IN ADULT RESPONSIBILITY", group: "Financial management", q: "1. I have difficulty managing my money." },
    { id: 's_ar_fin_2', part: "DIFFICULTIES IN ADULT RESPONSIBILITY", group: "Financial management", q: "2. I have large credit card debt." },
    { id: 's_ar_fin_3', part: "DIFFICULTIES IN ADULT RESPONSIBILITY", group: "Financial management", q: "3. I have difficulty balancing my checkbook." },
    { id: 's_ar_fin_4', part: "DIFFICULTIES IN ADULT RESPONSIBILITY", group: "Financial management", q: "4. I tend to file my tax forms late." },
    { id: 's_ar_fin_5', part: "DIFFICULTIES IN ADULT RESPONSIBILITY", group: "Financial management", q: "5. My financial record-keeping is chaotic." },
    { id: 's_ar_fin_6', part: "DIFFICULTIES IN ADULT RESPONSIBILITY", group: "Financial management", q: "6. Some years, I have not filed my income tax return." },
    { id: 's_ar_fin_7', part: "DIFFICULTIES IN ADULT RESPONSIBILITY", group: "Financial management", q: "7. I have a poor credit rating." },
    // PSYCHOLOGICAL ISSUES
    { id: 's_psy_dx_1', part: "PSYCHOLOGICAL ISSUES", group: "Diagnosed and treated for", q: "1. Depression" },
    { id: 's_psy_dx_2', part: "PSYCHOLOGICAL ISSUES", group: "Diagnosed and treated for", q: "2. Anxiety/panic disorder" },
    { id: 's_psy_dx_3', part: "PSYCHOLOGICAL ISSUES", group: "Diagnosed and treated for", q: "3. Bipolar disorder" },
    { id: 's_psy_dx_4', part: "PSYCHOLOGICAL ISSUES", group: "Diagnosed and treated for", q: "4. Post-traumatic stress disorder" },
    { id: 's_psy_dx_5', part: "PSYCHOLOGICAL ISSUES", group: "Diagnosed and treated for", q: "5. Obsessive-compulsive disorder" },
    { id: 's_psy_se_1', part: "PSYCHOLOGICAL ISSUES", group: "Low self-esteem", q: "1. I tend to hide many aspects of my life, fearing that I'll be judged negatively." },
    { id: 's_psy_se_2', part: "PSYCHOLOGICAL ISSUES", group: "Low self-esteem", q: "2. People think too highly of me, and I fear that I'll be 'found out.'" },
    { id: 's_psy_se_3', part: "PSYCHOLOGICAL ISSUES", group: "Low self-esteem", q: "3. I have often felt 'stupid' because I couldn't seem to accomplish things that others could." },
    { id: 's_psy_ma_1', part: "PSYCHOLOGICAL ISSUES", group: "Moodiness/anxiety", q: "1. I have felt demoralized by my failures." },
    { id: 's_psy_ma_2', part: "PSYCHOLOGICAL ISSUES", group: "Moodiness/anxiety", q: "2. I have felt depressed for 'no reason.'" },
    { id: 's_psy_ma_3', part: "PSYCHOLOGICAL ISSUES", group: "Moodiness/anxiety", q: "3. I am anxious and worry a lot." },
    { id: 's_psy_ma_4', part: "PSYCHOLOGICAL ISSUES", group: "Moodiness/anxiety", q: "4. I have fears and phobias." },
    { id: 's_psy_ma_5', part: "PSYCHOLOGICAL ISSUES", group: "Moodiness/anxiety", q: "5. I suffer from panic attacks." },
    { id: 's_psy_ma_6', part: "PSYCHOLOGICAL ISSUES", group: "Moodiness/anxiety", q: "6. I tend to be irritable and overreact to frustration." },
    { id: 's_psy_ma_7', part: "PSYCHOLOGICAL ISSUES", group: "Moodiness/anxiety", q: "7. My moods vary from day to day." },
    { id: 's_psy_oc_1', part: "PSYCHOLOGICAL ISSUES", group: "Obsessive/compulsive tendencies", q: "1. I have strong perfectionist tendencies." },
    { id: 's_psy_oc_2', part: "PSYCHOLOGICAL ISSUES", group: "Obsessive/compulsive tendencies", q: "2. Even in unimportant tasks, I feel compelled to do a perfect, micro-detailed job." },
    { id: 's_psy_oc_3', part: "PSYCHOLOGICAL ISSUES", group: "Obsessive/compulsive tendencies", q: "3. My perfectionism keeps me from completing tasks in a timely manner." },
    { id: 's_psy_oc_4', part: "PSYCHOLOGICAL ISSUES", group: "Obsessive/compulsive tendencies", q: "4. In my efforts to do a good job, I seem to make things more complicated than they need to be." },
    { id: 's_psy_oc_5', part: "PSYCHOLOGICAL ISSUES", group: "Obsessive/compulsive tendencies", q: "5. There are periods when I've become obsessed by a particular thought or concern." },
    { id: 's_psy_soc_1', part: "PSYCHOLOGICAL ISSUES", group: "Social/interpersonal problems", q: "1. My lateness and disorganization have been major points of conflict in important relationships." },
    { id: 's_psy_soc_2', part: "PSYCHOLOGICAL ISSUES", group: "Social/interpersonal problems", q: "2. I am separated and/or divorced." },
    { id: 's_psy_soc_3', part: "PSYCHOLOGICAL ISSUES", group: "Social/interpersonal problems", q: "3. I have been married more than once." },
    { id: 's_psy_soc_4', part: "PSYCHOLOGICAL ISSUES", group: "Social/interpersonal problems", q: "4. I can't seem to maintain friendships over the long term." },
    { id: 's_psy_soc_5', part: "PSYCHOLOGICAL ISSUES", group: "Social/interpersonal problems", q: "5. I tend to keep to myself." },
    { id: 's_psy_soc_6', part: "PSYCHOLOGICAL ISSUES", group: "Social/interpersonal problems", q: "6. I withdraw from other women for fear they will judge me." },
    { id: 's_psy_soc_7', part: "PSYCHOLOGICAL ISSUES", group: "Social/interpersonal problems", q: "7. I have always felt 'different' from others." },
    { id: 's_psy_soc_8', part: "PSYCHOLOGICAL ISSUES", group: "Social/interpersonal problems", q: "8. Sometimes, I misread people." },
    { id: 's_psy_soc_9', part: "PSYCHOLOGICAL ISSUES", group: "Social/interpersonal problems", q: "9. I am not a good listener and interrupt or think about other things while others are talking." },
    { id: 's_psy_frust_1', part: "PSYCHOLOGICAL ISSUES", group: "Low frustration tolerance", q: "1. I hate to wait." },
    { id: 's_psy_frust_2', part: "PSYCHOLOGICAL ISSUES", group: "Low frustration tolerance", q: "2. I become very frustrated and angry in traffic." },
    { id: 's_psy_frust_3', part: "PSYCHOLOGICAL ISSUES", group: "Low frustration tolerance", q: "3. I lose my temper if my children are noisy or argumentative." },
    { id: 's_psy_frust_4', part: "PSYCHOLOGICAL ISSUES", group: "Low frustration tolerance", q: "4. I quit tasks out of frustration." },
    { id: 's_psy_ua_1', part: "PSYCHOLOGICAL ISSUES", group: "Feelings of underachievement", q: "1. I should have done better in school." },
    { id: 's_psy_ua_2', part: "PSYCHOLOGICAL ISSUES", group: "Feelings of underachievement", q: "2. I have not achieved up to my potential in my career." },
    { id: 's_psy_ua_3', part: "PSYCHOLOGICAL ISSUES", group: "Feelings of underachievement", q: "3. I haven't reached the life goals I set for myself." },
    { id: 's_psy_ua_4', part: "PSYCHOLOGICAL ISSUES", group: "Feelings of underachievement", q: "4. I feel disappointed in my achievements." },
    { id: 's_psy_crit_1', part: "PSYCHOLOGICAL ISSUES", group: "Feeling criticized/misunderstood", q: "1. I am very sensitive to criticism." },
    { id: 's_psy_crit_2', part: "PSYCHOLOGICAL ISSUES", group: "Feeling criticized/misunderstood", q: "2. I feel that I am viewed negatively." },
    { id: 's_psy_crit_3', part: "PSYCHOLOGICAL ISSUES", group: "Feeling criticized/misunderstood", q: "3. The people close to me don't understand my struggles to manage my life." },
    { id: 's_psy_crit_4', part: "PSYCHOLOGICAL ISSUES", group: "Feeling criticized/misunderstood", q: "4. I suffered 'classroom traumas and humiliations,' which still haunt me and affect my life." },
    // OTHER DIFFICULTIES
    { id: 's_oth_horm_1', part: "OTHER DIFFICULTIES", group: "Hormonal issues", q: "1. I have severe PMS symptoms, including moodiness, irritability, and low frustration tolerance." },
    { id: 's_oth_horm_2', part: "OTHER DIFFICULTIES", group: "Hormonal issues", q: "2. My PMS symptoms have become worse over the years." },
    { id: 's_oth_horm_3', part: "OTHER DIFFICULTIES", group: "Hormonal issues", q: "3. My AD/HD symptoms decreased during pregnancy." },
    { id: 's_oth_horm_4', part: "OTHER DIFFICULTIES", group: "Hormonal issues", q: "4. Right before my period, my AD/HD symptoms become worse." },
    { id: 's_oth_horm_5', part: "OTHER DIFFICULTIES", group: "Hormonal issues", q: "5. I did well in elementary school, but started having difficulty in middle or high school." },
    { id: 's_oth_sleep_1', part: "OTHER DIFFICULTIES", group: "Sleep problems", q: "1. I am a 'night owl' and rarely go to sleep at a 'reasonable' hour." },
    { id: 's_oth_sleep_2', part: "OTHER DIFFICULTIES", group: "Sleep problems", q: "2. I have difficulty falling asleep because my mind is racing." },
    { id: 's_oth_sleep_3', part: "OTHER DIFFICULTIES", group: "Sleep problems", q: "3. If I could sleep on 'my' schedule, I'd sleep from 3 AM to 11 AM." },
    { id: 's_oth_fibro_1', part: "OTHER DIFFICULTIES", group: "Fibromyalgia", q: "1. I have been diagnosed with fibromyalgia." },
    { id: 's_oth_fibro_2', part: "OTHER DIFFICULTIES", group: "Fibromyalgia", q: "2. I have a history of chronic muscle and/or joint pain." },
    { id: 's_oth_eat_1', part: "OTHER DIFFICULTIES", group: "Problem eating patterns", q: "1. I often eat to calm myself." },
    { id: 's_oth_eat_2', part: "OTHER DIFFICULTIES", group: "Problem eating patterns", q: "2. I tend to overeat." },
    { id: 's_oth_eat_3', part: "OTHER DIFFICULTIES", group: "Problem eating patterns", q: "3. I have had an eating disorder at some time in my life." },
    { id: 's_oth_eat_4', part: "OTHER DIFFICULTIES", group: "Problem eating patterns", q: "4. I have abused laxatives or purged to lose weight." },
    { id: 's_oth_sub_1', part: "OTHER DIFFICULTIES", group: "Substance abuse/addiction", q: "1. I have a history of substance abuse." },
    { id: 's_oth_sub_2', part: "OTHER DIFFICULTIES", group: "Substance abuse/addiction", q: "2. I have abused alcohol." },
    { id: 's_oth_sub_3', part: "OTHER DIFFICULTIES", group: "Substance abuse/addiction", q: "3. I smoke cigarettes and have been unable to quit." },
    { id: 's_oth_med_1', part: "OTHER DIFFICULTIES", group: "Patterns of self-medication", q: "1. I keep myself going throughout the day with coffee, tea, and colas." },
    { id: 's_oth_med_2', part: "OTHER DIFFICULTIES", group: "Patterns of self-medication", q: "2. I have used cigarettes to help increase my concentration." },
    { id: 's_oth_med_3', part: "OTHER DIFFICULTIES", group: "Patterns of self-medication", q: "3. I have regularly used marijuana, alcohol and/or food to calm myself." },
    { id: 's_oth_abu_1', part: "OTHER DIFFICULTIES", group: "Abuse/trauma", q: "1. I was repeatedly humiliated or psychologically abused in the classroom as a girl." },
    { id: 's_oth_abu_2', part: "OTHER DIFFICULTIES", group: "Abuse/trauma", q: "2. I have been in an abusive relationship as an adult." },
    { id: 's_oth_abu_3', part: "OTHER DIFFICULTIES", group: "Abuse/trauma", q: "3. I have been physically, sexually, or emotionally abused." },
    { id: 's_oth_abu_4', part: "OTHER DIFFICULTIES", group: "Abuse/trauma", q: "4. Events that are not particularly traumatic for others trigger intense and repetitive anxiety reactions in me." },
    { id: 's_oth_abu_5', part: "OTHER DIFFICULTIES", group: "Abuse/trauma", q: "5. I have nightmares, flashbacks, and/or extreme anxiety as a result of traumatic event(s) in my past." }
];

// Merge additional SASI questions
QUESTIONS.sasi = QUESTIONS.sasi.concat(SASI_ADDITIONAL);
